version: '3.3'

services:
  app:
    build: '.'
    command: 'make test'
    volumes:
      - .:/app:cached
      - bundler-data:/usr/local/bundle/
      - bin-data:/usr/local/bin/
    ports:
      - "3000:3000"


volumes:
  bundler-data:
  bin-data:
